name: Firebase Push Scheduler

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  push_to_firebase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Push to Firebase
      env:
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        FIREBASE_DATABASE_SECRET: ${{ secrets.FIREBASE_DATABASE_SECRET }}
      run: |
        curl -X PUT -d '1' "$FIREBASE_DATABASE_URL/path/to/your/data.json?auth=$FIREBASE_DATABASE_SECRET"
